name: Edify Deployment
on: workflow_dispatch
jobs:
  sonarqube:
    runs-on: ubuntu-latest    
    steps:
      - name: Clone Code
        uses: actions/checkout@v5.0.0
      - name: Sonar Analysis
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  build:
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v5.0.0
      - name: Build Docker Image
        run: docker build -t ${{vars.DOCKER_USERNAME}}/edify:latest .
      - name: Docker login
        uses: docker/login-action@v3.6.0
        with: 
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Push Docker Image
        run: docker push ${{vars.DOCKER_USERNAME}}/edify:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull the Image
        run: docker pull ${{vars.DOCKER_USERNAME}}/edify:latest
      - name: Run the Container
        run: docker container run -dt --name edify -p 80:80 ${{vars.DOCKER_USERNAME}}/edify:latest
      - name: Check Container
        run: docker container ls





      
